name: orient
description: "Attendance System for Companies."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  animated_custom_dropdown: ^3.1.1
  flutter_bloc:
  pretty_dio_logger:
  shimmer:
  bloc:
  webview_flutter:
  # Widgets starting auto play animation when mounted. It is already possible to animate the list and icons.
  auto_animated: 3.2.0
  auto_size_text: 3.0.0
  cached_network_image: 3.3.1
  collection: 1.18.0
  connectivity_plus: ^6.0.5
  cupertino_icons: 1.0.6
  device_info_plus: ^11.0.0
  dio: 5.5.0
  easy_localization: 3.0.7
  file_picker: ^8.1.2
  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.3
  flutter:
    sdk: flutter


  flutter_localizations:
    sdk: flutter
  flutter_map: ^7.0.2
  flutter_native_splash: 2.4.1
  flutter_staggered_grid_view: ^0.6.2
  flutter_svg: 2.0.10+1
  flutter_web_plugins:
    sdk: flutter
  font_awesome_flutter: 10.7.0
  go_router: 14.2.0
  graphview: 1.2.0
  # QR.Flutter is a Flutter library for simple and fast QR code rendering via a Widget or custom painter.
  qr_flutter: 4.1.0
  # A flutter package that helps copy text to clipboard and paste from clipboard.
  clipboard: 0.1.3
  # A Dart package that helps to implement value based equality without needing to explicitly override == and hashCode.
  equatable: 2.0.5
  # QR code scanner that can be embedded inside flutter. It uses zxing in Android and MTBBarcode scanner in iOS.
  qr_code_scanner: 1.0.1
  #package to show video
  chewie: ^1.8.5
  video_player: ^2.9.2

  #  show image in full screen
  full_screen_image: ^2.0.0

  # Flutter plugin to scan for nearby visible WiFi access points.
  # wifi_scan: 0.4.1
  # Flutter plugin for connecting and communicating with Bluetooth Low Energy devices, on Android and iOS
  flutter_blue_plus: 1.32.12
  # Lightweight and blazing fast key-value database written in pure Dart. Strongly encrypted using AES-256.
  hive: 2.2.3
  html: 0.15.4
  http_parser: 4.0.2
  image_picker: 1.1.2
  intl: 0.19.0
  intl_phone_field: 3.2.0
  latlong2: ^0.9.1
  local_auth: 2.2.0
  location: 6.0.2
  mime: 1.0.5
  network_info_plus: 5.0.3
  nfc_manager: 3.5.0
  package_info_plus: ^8.0.3
  path: 1.9.0
  path_provider: 2.1.4
  permission_handler: 11.3.1
  photo_view: ^0.14.0
  provider: 6.1.2
  rename: 3.0.2
  shared_preferences: 2.2.3
  soundpool: 2.4.1
  syncfusion_flutter_calendar: 26.2.7
  syncfusion_flutter_pdf: 26.1.40
  universal_html: 2.2.4
  url_launcher: 6.3.0
  yaml: 3.1.2

dev_dependencies:
  flutter_launcher_icons: 0.13.1
  flutter_lints: 3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/json/lang/
    - assets/icons/
    - pubspec.yaml
    - assets/images/
    - assets/images/alerts_images/
    - assets/images/svg/
    - assets/images/png/
    - assets/icons/
    - assets/images/splash_images/
    - assets/images/general_images/
    - assets/images/onboarding_images/
    - assets/images/login_images/
    - assets/images/home_images/
    - assets/images/home_images/bottom_bar_images/
    - assets/images/home_images/floating_actions_buttons_images/
    - assets/images/home_images/appbar_images/
    - assets/images/notifications_images/
    - assets/images/profiles_images/
    - assets/images/company_info_images/
    - assets/images/fingerprints_images/
    - assets/images/reward_penalties_images/
    - assets/images/painter_main_screen_images/
    - assets/images/teams_images/
    - assets/images/ecommerce/png/
    - assets/images/ecommerce/svg/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Black.ttf
        - asset: assets/fonts/poppins/Poppins-BlackItalic.ttf
        - asset: assets/fonts/poppins/Poppins-Bold.ttf
        - asset: assets/fonts/poppins/Poppins-BoldItalic.ttf
        - asset: assets/fonts/poppins/Poppins-ExtraBold.ttf
        - asset: assets/fonts/poppins/Poppins-ExtraBoldItalic.ttf
        - asset: assets/fonts/poppins/Poppins-ExtraLight.ttf
        - asset: assets/fonts/poppins/Poppins-ExtraLightItalic.ttf
        - asset: assets/fonts/poppins/Poppins-Italic.ttf
        - asset: assets/fonts/poppins/Poppins-Light.ttf
        - asset: assets/fonts/poppins/Poppins-LightItalic.ttf
        - asset: assets/fonts/poppins/Poppins-Medium.ttf
        - asset: assets/fonts/poppins/Poppins-MediumItalic.ttf
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
        - asset: assets/fonts/poppins/Poppins-SemiBold.ttf
        - asset: assets/fonts/poppins/Poppins-SemiBoldItalic.ttf
        - asset: assets/fonts/poppins/Poppins-Thin.ttf
        - asset: assets/fonts/poppins/Poppins-ThinItalic.ttf
    - family: Montserrat-Arabic
      fonts:
        - asset: assets/fonts/montserrat/Montserrat-Arabic.ttf
