name: orient
description: "Attendance System for Companies."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  cupertino_icons: 1.0.6
  collection: 1.18.0
  # A wrapper around InheritedWidget to make them easier to use and more reusable.
  provider: 6.1.2
  # A declarative router for Flutter based on Navigation 2 supporting deep linking, data-driven routes and more.
  go_router: 14.2.0
  # Widgets starting auto play animation when mounted. It is already possible to animate the list and icons.
  auto_animated: 3.2.0
  # Flutter plugin providing detailed information about the device (make, model, etc.), and Android or iOS version the app is running on.
  device_info_plus: ^11.0.0
  # Flutter plugin for querying information about the application package, such as CFBundleVersion on iOS or versionCode on Android.
  package_info_plus: ^8.0.3
  # Flutter plugin for launching a URL. Supports web, phone, SMS, and email schemes
  url_launcher: 6.3.0
  # Flutter plugin for reading and writing simple key-value pairs. Wraps NSUserDefaults on iOS and SharedPreferences on Android
  shared_preferences: 2.2.3
  # Contains code to deal with internationalized/localized messages, date and number formatting and parsing, bi-directional text, and other internationalization issues.
  intl: 0.19.0
  # A composable, multi-platform, Future-based API for HTTP requests.
  http: ^1.2.2
  # A platform-independent package for parsing and serializing HTTP formats.
  http_parser: 4.0.2
  # A string-based path manipulation library. All of the path operations you know and love, with solid support for Windows, POSIX (Linux and Mac OS X), and the web.
  path: 1.9.0
  # A Flutter Sound Pool for playing short audio files. Sound tracks are cached in memory and played directly from cache.
  soundpool: 2.4.1
  # Flutter plugin for Firebase Core, enabling connecting to multiple Firebase apps.
  firebase_core: ^3.6.0
  # Flutter plugin for Firebase Cloud Messaging, a cross-platform messaging solution that lets you reliably deliver messages on Android , iOS and Web.
  firebase_messaging: ^15.1.3
  # Easy and Fast internationalizing and localization your Flutter Apps, this package simplify the internationalizing process .
  # Easy and Fast internationalizing and firelocalization your Flutter Apps, this package simplify the internationalizing process .
  easy_localization: 3.0.7
  # A 'dart:html' that works in all platforms, including Flutter and server-side. Eases cross-platform development and HTML / XML processing.
  universal_html: 2.2.4
  # A powerful HTTP networking package, supports Interceptors, Aborting and canceling a request, Custom adapters, Transformers, etc.
  dio: 5.5.0
  # Flutter plugin for discovering the state of the network (WiFi & mobile/cellular) connectivity on Android and iOS.
  connectivity_plus: ^6.0.5
  # Utilities for handling media (MIME) types, including determining a type from a file extension and file contents.
  mime: 1.0.5
  # Flutter plugin for discovering information (e.g. WiFi details) of the network.
  network_info_plus: 5.0.3
  # Flutter plugin for Android and iOS devices to allow local authentication via fingerprint, touch ID, face ID, passcode, pin, or pattern.
  local_auth: 2.2.0
  # APIs for parsing and manipulating HTML content outside the browser.
  html: 0.15.4
  # A complete api for audio playback and recording. Audio player, audio recorder.
  # flutter_sound: 9.6.0
  # Permission plugin for Flutter. This plugin provides a cross-platform (iOS, Android)clear API to request and check permissions.
  permission_handler: 11.3.1
  # Cross-platform plugin for easy access to device's location in real-time.
  location: 6.0.2
  # A package that allows you to use a native file explorer to pick single or multiple absolute file paths, with extension filtering support.
  file_picker: ^8.1.2
  # Flutter plugin for selecting images
  image_picker: 1.1.2
  # The Flutter PDF is a library written natively in Dart for creating, reading, editing, and securing PDF files in Android, iOS, and web platforms.
  syncfusion_flutter_pdf: 26.1.40
  # Flutter plugin for getting commonly used locations on host platform file systems, such as the temp and app data directories.
  path_provider: 2.1.4
  # Flutter widget that automatically resizes text to fit perfectly within its bounds.
  auto_size_text: 3.0.0
  # A customised Flutter TextFormField to input international phone number along with country code.
  intl_phone_field: 3.2.0
  # Customize Flutter's default white native splash screen with background color and splash image. Supports dark mode, full screen, and more.
  flutter_native_splash: 2.4.1
  # An SVG rendering and widget library for Flutter, which allows painting and displaying Scalable Vector Graphics 1.1 files.
  flutter_svg: 2.0.10+1
  # Flutter library to load and cache network images. Can also be used with placeholder and error widgets.
  cached_network_image: 3.3.1
  # The Flutter Calendar widget has nine built-in configurable views that provide basic functionalities for scheduling and representing appointments/events efficiently.
  syncfusion_flutter_calendar: 26.2.7
  # The Font Awesome Icon pack available as Flutter Icons. Provides 2000 additional icons to use in your apps.
  font_awesome_flutter: 10.7.0
  # A parser for YAML, a human-friendly data serialization standard
  yaml: 3.1.2
  # GraphView is used to display data in graph structures. It can display Tree layout, Directed and Layered graph. Useful for Family Tree, Hierarchy View.
  graphview: 1.2.0
  # QR.Flutter is a Flutter library for simple and fast QR code rendering via a Widget or custom painter.
  qr_flutter: 4.1.0
  # A flutter package that helps copy text to clipboard and paste from clipboard.
  clipboard: 0.1.3
  # A Dart package that helps to implement value based equality without needing to explicitly override == and hashCode.
  equatable: 2.0.5
  # QR code scanner that can be embedded inside flutter. It uses zxing in Android and MTBBarcode scanner in iOS.
  qr_code_scanner: 1.0.1
  # Flutter plugin to scan for nearby visible WiFi access points.
  # wifi_scan: 0.4.1
  # Flutter plugin for connecting and communicating with Bluetooth Low Energy devices, on Android and iOS
  flutter_blue_plus: 1.32.12
  # Flutter plugin for accessing the NFC features on Android and iOS.
  nfc_manager: 3.5.0
  # Lightweight and blazing fast key-value database written in pure Dart. Strongly encrypted using AES-256.
  hive: 2.2.3
  rename: 3.0.2



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 3.0.0
  # A package which simplifies the task of updating your Flutter app's launcher icon.
  flutter_launcher_icons: 0.13.1

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/json/lang/
    - pubspec.yaml
    - assets/images/alerts_images/
    - assets/images/splash_images/
    - assets/images/general_images/
    - assets/images/onboarding_images/
    - assets/images/login_images/
    - assets/images/home_images/
    - assets/images/home_images/bottom_bar_images/
    - assets/images/home_images/floating_actions_buttons_images/
    - assets/images/home_images/appbar_images/
    - assets/images/notifications_images/
    - assets/images/profiles_images/   
    - assets/images/company_info_images/
    - assets/images/fingerprints_images/     
    - assets/images/reward_penalties_images/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Black.ttf
        - asset: assets/fonts/poppins/Poppins-BlackItalic.ttf
        - asset: assets/fonts/poppins/Poppins-Bold.ttf
        - asset: assets/fonts/poppins/Poppins-BoldItalic.ttf
        - asset: assets/fonts/poppins/Poppins-ExtraBold.ttf
        - asset: assets/fonts/poppins/Poppins-ExtraBoldItalic.ttf
        - asset: assets/fonts/poppins/Poppins-ExtraLight.ttf
        - asset: assets/fonts/poppins/Poppins-ExtraLightItalic.ttf
        - asset: assets/fonts/poppins/Poppins-Italic.ttf
        - asset: assets/fonts/poppins/Poppins-Light.ttf
        - asset: assets/fonts/poppins/Poppins-LightItalic.ttf
        - asset: assets/fonts/poppins/Poppins-Medium.ttf
        - asset: assets/fonts/poppins/Poppins-MediumItalic.ttf
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
        - asset: assets/fonts/poppins/Poppins-SemiBold.ttf
        - asset: assets/fonts/poppins/Poppins-SemiBoldItalic.ttf
        - asset: assets/fonts/poppins/Poppins-Thin.ttf
        - asset: assets/fonts/poppins/Poppins-ThinItalic.ttf
    - family: Montserrat-Arabic
      fonts:
        - asset: assets/fonts/montserrat/Montserrat-Arabic.ttf
